version: '3.6'

services:  
  chat_server:
    build: ./
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    restart: on-failure
    networks:
      - common
networks:
  common:
